[versions]

#======Kotlin
kotlin = "2.3.20-dev-2461"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
jbCompose = "1.10.0-beta01"
jbComposeMaterial3 = "1.9.0"
ktor = "3.3.2"

#=====Google
ksp = "2.3.2"

#======Android
androidCompileSdk = "36"
androidTargetSdk = "36"
androidMinSdk = "24"
androidGradlePlugin = "8.13.1"
androidMaterial = "1.13.0"
androidxActivityKtx = "1.11.0"
androidxLifecycle = "2.9.4"

#======Multiplatform
kermit = "2.0.8"
sqldelight = "2.2.1"
koin = "4.1.1"
turbine = "1.2.1"

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "jbCompose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]

#======Gradle
gradle-android-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

#======Jetbrains
test-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
test-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "jbCompose" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "jbCompose" }
compose-runtimeSaveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "jbCompose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "jbCompose" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "jbCompose" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "jbComposeMaterial3" }
compose-material3-windowSizeClass = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "jbComposeMaterial3" }
compose-componentsResources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "jbCompose" }

#======Multiplatform
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

sqldelight-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-ios-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

test-koin = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
test-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

#======Android
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityKtx" }

[bundles]

ktor = [
    "ktor-client-core",
    "ktor-serialization",
    "ktor-contentNegotiation",
    "ktor-logging"
]

compose-multiplatform = [
    "compose-foundation",
    "compose-runtime",
    "compose-runtimeSaveable",
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-material3-windowSizeClass",
    "compose-componentsResources"
]